#---------------------------------------------------#
## 配置文件需要放置在 $HOME/.config/clash/*.yaml

## 这份文件是clashX的基础配置文件，请尽量新建配置文件进行修改。
## ！！！只有这份文件的端口设置会随ClashX启动生效

## 如果您不知道如何操作，请参阅 官方Github文档 https://github.com/Dreamacro/clash/blob/dev/README.md
#---------------------------------------------------#

# (HTTP and SOCKS5 in one port)
mixed-port: 7890
# RESTful API for clash
external-controller: 127.0.0.1:9090
allow-lan: false
mode: rule
log-level: warning

dns:
  enable: true
  ipv6: false
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
    - 8.8.8.8
  fallback:
    - tls://1.0.0.1:853
    - tls://dns.google:853
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4

proxies:

  - name: "美国"
    type: vmess
    server: usa1v2.jsss.ltd
    port: 44102
    uuid: 1b957d7b-dbb2-11e9-8ee6-00163e108217
    alterId: 0
    cipher: auto
    tls: true
    network: ws
    ws-path: /cpyhyfd3
  - name: "美国2"
    type: vmess
    server: usa2v2.jsss.ltd
    port: 44102
    uuid: 1b957d7b-dbb2-11e9-8ee6-00163e108217
    alterId: 0
    cipher: auto
    tls: true
    network: ws
    ws-path: /cpyhyfd3
  - name: "香港1"
    type: vmess
    server: hk1v2.jsss.ltd
    port: 44202
    uuid: 1b957d7b-dbb2-11e9-8ee6-00163e108217
    alterId: 0
    cipher: auto
    tls: true
    network: ws
    ws-path: /cpyhyfd3
  - name: "俄罗斯"
    type: vmess
    server: ru1v2.jsss.ltd
    port: 443
    uuid: 1b957d7b-dbb2-11e9-8ee6-00163e108217
    alterId: 2
    cipher: auto
    tls: true
    network: ws
    ws-path: /cpyhyfd3
  - name: "韩国"
    type: vmess
    server: kr1v2.jsss.ltd
    port: 443
    uuid: 1b957d7b-dbb2-11e9-8ee6-00163e108217
    alterId: 2
    cipher: auto
    tls: true
    network: ws
    ws-path: /cpyhyfd3
  - name: "新加坡"
    type: vmess
    server: sg1v2.jsss.ltd
    port: 443
    uuid: 1b957d7b-dbb2-11e9-8ee6-00163e108217
    alterId: 2
    cipher: auto
    tls: true
    network: ws
    ws-path: /cpyhyfd3
  - name: "日本"
    type: vmess
    server: jp1v2-tls.jsss.ltd
    port: 44602
    uuid: 1b957d7b-dbb2-11e9-8ee6-00163e108217
    alterId: 0
    cipher: auto
    tls: true
    network: ws
    ws-path: /cpyhyfd3



# 服务器节点订阅
proxy-providers:



proxy-groups:
  - name: "节点列表"
    type: select
    proxies:
      - 美国
      - 美国2
      - 香港1
      - 俄罗斯
      - 韩国
      - 新加坡
      - 日本



  # 代理节点选择
  - name: "PROXY"
    type: select
    proxies:
      - 节点列表

  # 白名单模式 PROXY, 黑名单模式 DIRECT, 不知道别动
  - name: "MATCH"
    type: select
    proxies:
      - PROXY

  # 国际流媒体服务
  - name: "Streaming"
    type: select
    proxies:
      - PROXY

  # 中国流媒体服务（面向海外版本）
  - name: "StreamingSE"
    type: select
    proxies:
      - DIRECT
      - PROXY



# # proxy-groups:
# Proxy Group:
# - { name: "Proxy", type: select, proxies: ["socks", "auto"] }

# rules:
#   - DOMAIN-SUFFIX,google.com,DIRECT
#   - DOMAIN-KEYWORD,google,DIRECT
#   - DOMAIN,google.com,DIRECT
#   - DOMAIN-SUFFIX,ad.com,REJECT
#   - GEOIP,CN,DIRECT
#   - MATCH,DIRECT


rule-providers:
  reject:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
    path: ./ruleset/reject.yaml
    interval: 86400

  icloud:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt"
    path: ./ruleset/icloud.yaml
    interval: 86400

  apple:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt"
    path: ./ruleset/apple.yaml
    interval: 86400

  google:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt"
    path: ./ruleset/google.yaml
    interval: 86400

  proxy:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt"
    path: ./ruleset/proxy.yaml
    interval: 86400

  direct:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt"
    path: ./ruleset/direct.yaml
    interval: 86400

  private:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt"
    path: ./ruleset/private.yaml
    interval: 86400

  gfw:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
    path: ./ruleset/gfw.yaml
    interval: 86400

  greatfire:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/greatfire.txt"
    path: ./ruleset/greatfire.yaml
    interval: 86400

  tld-not-cn:
    type: http
    behavior: domain
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt"
    path: ./ruleset/tld-not-cn.yaml
    interval: 86400

  telegramcidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt"
    path: ./ruleset/telegramcidr.yaml
    interval: 86400

  cncidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt"
    path: ./ruleset/cncidr.yaml
    interval: 86400

  lancidr:
    type: http
    behavior: ipcidr
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt"
    path: ./ruleset/lancidr.yaml
    interval: 86400



rules:
  - PROCESS-NAME,v2ray,DIRECT
  - PROCESS-NAME,xray,DIRECT
  - PROCESS-NAME,naive,DIRECT
  - PROCESS-NAME,trojan,DIRECT
  - PROCESS-NAME,trojan-go,DIRECT
  - PROCESS-NAME,ss-local,DIRECT
  - PROCESS-NAME,privoxy,DIRECT
  - PROCESS-NAME,leaf,DIRECT
  - PROCESS-NAME,v2ray.exe,DIRECT
  - PROCESS-NAME,xray.exe,DIRECT
  - PROCESS-NAME,naive.exe,DIRECT
  - PROCESS-NAME,trojan.exe,DIRECT
  - PROCESS-NAME,trojan-go.exe,DIRECT
  - PROCESS-NAME,ss-local.exe,DIRECT
  - PROCESS-NAME,privoxy.exe,DIRECT
  - PROCESS-NAME,leaf.exe,DIRECT
  - PROCESS-NAME,Surge,DIRECT
  - PROCESS-NAME,Surge 2,DIRECT
  - PROCESS-NAME,Surge 3,DIRECT
  - PROCESS-NAME,Surge 4,DIRECT
  - PROCESS-NAME,Surge%202,DIRECT
  - PROCESS-NAME,Surge%203,DIRECT
  - PROCESS-NAME,Surge%204,DIRECT
  - PROCESS-NAME,Thunder,DIRECT
  - PROCESS-NAME,DownloadService,DIRECT
  - PROCESS-NAME,qBittorrent,DIRECT
  - PROCESS-NAME,Transmission,DIRECT
  - PROCESS-NAME,fdm,DIRECT
  - PROCESS-NAME,aria2c,DIRECT
  - PROCESS-NAME,Folx,DIRECT
  - PROCESS-NAME,NetTransport,DIRECT
  - PROCESS-NAME,uTorrent,DIRECT
  - PROCESS-NAME,WebTorrent,DIRECT
  - PROCESS-NAME,aria2c.exe,DIRECT
  - PROCESS-NAME,BitComet.exe,DIRECT
  - PROCESS-NAME,fdm.exe,DIRECT
  - PROCESS-NAME,NetTransport.exe,DIRECT
  - PROCESS-NAME,qbittorrent.exe,DIRECT
  - PROCESS-NAME,Thunder.exe,DIRECT
  - PROCESS-NAME,ThunderVIP.exe,DIRECT
  - PROCESS-NAME,transmission-daemon.exe,DIRECT
  - PROCESS-NAME,transmission-qt.exe,DIRECT
  - PROCESS-NAME,uTorrent.exe,DIRECT
  - PROCESS-NAME,WebTorrent.exe,DIRECT
  - DOMAIN,clash.razord.top,DIRECT
  - DOMAIN,yacd.haishan.me,DIRECT
  - RULE-SET,private,DIRECT
  - RULE-SET,reject,REJECT
  - RULE-SET,icloud,DIRECT
  - RULE-SET,apple,DIRECT
  - RULE-SET,google,DIRECT
  - RULE-SET,proxy,PROXY
  - RULE-SET,direct,DIRECT
  - RULE-SET,telegramcidr,PROXY
  - GEOIP,,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,PROXY
