[manager]
prepend_keymap = [
	{ on = ["u"], run = "arrow -1", desc = "Move cursor up" },
  { on = ["e"], run = "arrow 1", desc = "Move cursor down" },
	{ on = ["U"], run = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = ["E"], run = "arrow 5", desc = "Move cursor down 5 lines" },

  { on = ["n"], run = "leave", desc = "Go back to the parent directory" },
  { on = ["i"], run = "plugin --sync smart-enter", desc = "Enter the child directory" },

	{ on = ["S"], run = "quit", desc = "Exit the process" },
]
append_keymap = [
	{ on = [ "<C-b>" ], run = 'my-fev-command2', desc = "Just for test!" },
]
