[manager]
prepend_keymap = [
	{ on = ["u"], exec = "arrow -1", desc = "Move cursor up" },
  { on = ["e"], exec = "arrow 1", desc = "Move cursor down" },
	{ on = ["U"], exec = "arrow -5", desc = "Move cursor up 5 lines" },
  { on = ["E"], exec = "arrow 5", desc = "Move cursor down 5 lines" },

  { on = ["n"], exec = "leave", desc = "Go back to the parent directory" },
  { on = ["i"], exec = "plugin --sync smart-enter", desc = "Enter the child directory" },

	{ on = ["S"], exec = "quit", desc = "Exit the process" },
]
append_keymap = [
	{ on = [ "<C-b>" ], exec = 'my-fev-command2', desc = "Just for test!" },
]
